//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1ConsoleApp1.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimeNum", ReplyAction="http://tempuri.org/IService1/PrimeNumResponse")]
        int PrimeNum(int n1, bool isPrime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimeNum", ReplyAction="http://tempuri.org/IService1/PrimeNumResponse")]
        System.Threading.Tasks.Task<int> PrimeNumAsync(int n1, bool isPrime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumDigits", ReplyAction="http://tempuri.org/IService1/SumDigitsResponse")]
        int SumDigits(int n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumDigits", ReplyAction="http://tempuri.org/IService1/SumDigitsResponse")]
        System.Threading.Tasks.Task<int> SumDigitsAsync(int n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        string ReverseString(string s1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string s1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHTMLTag", ReplyAction="http://tempuri.org/IService1/PrintHTMLTagResponse")]
        string PrintHTMLTag(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHTMLTag", ReplyAction="http://tempuri.org/IService1/PrintHTMLTagResponse")]
        System.Threading.Tasks.Task<string> PrintHTMLTagAsync(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sort5Num", ReplyAction="http://tempuri.org/IService1/Sort5NumResponse")]
        string Sort5Num(string s1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sort5Num", ReplyAction="http://tempuri.org/IService1/Sort5NumResponse")]
        System.Threading.Tasks.Task<string> Sort5NumAsync(string s1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : A1ConsoleApp1.ServiceReference5.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<A1ConsoleApp1.ServiceReference5.IService1>, A1ConsoleApp1.ServiceReference5.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int PrimeNum(int n1, bool isPrime) {
            return base.Channel.PrimeNum(n1, isPrime);
        }
        
        public System.Threading.Tasks.Task<int> PrimeNumAsync(int n1, bool isPrime) {
            return base.Channel.PrimeNumAsync(n1, isPrime);
        }
        
        public int SumDigits(int n1) {
            return base.Channel.SumDigits(n1);
        }
        
        public System.Threading.Tasks.Task<int> SumDigitsAsync(int n1) {
            return base.Channel.SumDigitsAsync(n1);
        }
        
        public string ReverseString(string s1) {
            return base.Channel.ReverseString(s1);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string s1) {
            return base.Channel.ReverseStringAsync(s1);
        }
        
        public string PrintHTMLTag(string s1, string s2) {
            return base.Channel.PrintHTMLTag(s1, s2);
        }
        
        public System.Threading.Tasks.Task<string> PrintHTMLTagAsync(string s1, string s2) {
            return base.Channel.PrintHTMLTagAsync(s1, s2);
        }
        
        public string Sort5Num(string s1) {
            return base.Channel.Sort5Num(s1);
        }
        
        public System.Threading.Tasks.Task<string> Sort5NumAsync(string s1) {
            return base.Channel.Sort5NumAsync(s1);
        }
    }
}
